### ISSUE TITLE
Criação do Diagrama de Atividades

### ISSUE THREAD

**Issue by lucasgbezerra** [UnBArqDsw2021-1/2021.1_G5_ProjetoDonner#32]
### Descrição
Criação do diagrama de atividades

### Critérios de aceitação

- [x] A ortografia do documento está correta
- [x] O documento está coerente com o artefato que representa
- [x] Os Diagramas estão coerentes

**Comment by marcosadrianonery** [comment]
Revisão do documento realizada.
