### ISSUE TITLE
Criação do Diagrama de Estados

### ISSUE THREAD

**Issue by lucasgbezerra** [UnBArqDsw2021-1/2021.1_G5_ProjetoDonner#33]
### Descrição
Criação do Diagrama de Estados

### Critérios de aceitação

- [x] A ortografia do documento está correta
- [x] O documento está coerente com o artefato que representa
- [x] Os Diagramas estão coerentes

**Comment by kleidson-alves** [comment]
A revisão do documento foi realizada e foi constatado que ele atendeu aos critérios de aceitação
