### ISSUE TITLE
Criação das Histórias de usuário

### ISSUE THREAD

**Issue by wellpriz** [UnBArqDsw2021-1/2021.1_G5_ProjetoDonner#39]
### Descrição
Criação das Histórias de usuário

### Critérios de aceitação

- [x] A ortografia do documento está correta
- [x] O documento está coerente com o artefato que representa
- [x] Os Diagramas estão coerentes

**Comment by kleidson-alves** [comment]
Histórias de usuário foram criadas de acordo com os critérios
