### ISSUE TITLE
Criar Documento GoF Criacional

### ISSUE THREAD

**Issue by lucas229** [UnBArqDsw2021-1/2021.1_G5_ProjetoDonner#48]
### Descrição
Documento GoF Criacional

### Critérios de aceitação

- [x] A ortografia do documento está correta
- [x] O documento está coerente com o artefato que representa

**Comment by wellpriz** [comment]
A revisão do documento foi realizada e foi constatado que ele atendeu aos critérios de aceitação.

**Comment by wellpriz** [comment]
A revisão do documento foi realizada e foi constatado que ele atendeu aos critérios de aceitação
